### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mmorihiro** [mmorihiro/matchland#50]
## 再現方法
2回目以降に6列目を選択する。
## StackTrace
```
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
	at mmorihiro.larger_circle.view.PuzzleView.getBubbleFromPoint(PuzzleView.kt:34)
	at mmorihiro.larger_circle.controller.TouchActionKt.onTouchDragged(TouchAction.kt:51)
	at mmorihiro.larger_circle.controller.PuzzleController$view$2.invoke(PuzzleController.kt:15)
	at mmorihiro.larger_circle.controller.PuzzleController$view$2.invoke(PuzzleController.kt:11)
	at mmorihiro.larger_circle.view.PuzzleView.touchDragged(PuzzleView.kt:74)
	at com.badlogic.gdx.InputMultiplexer.touchDragged(InputMultiplexer.java:102)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:335)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by mmorihiro** [comment]
Fixed with #51
